version: '3.8'

services:
  server:
    image: todo-backend
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
    environment: 
      - PORT=3001
      - REDIS_URL=//cache:6379
      - MONGO_URL=mongodb://the_username:the_password@database:27017/the_database
  mongo:
    container_name: database
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    ports:
      - 27017:27017
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
  redis:
    container_name: cache
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data