version: '3.8'

services:
  app:
    container_name: approt-doc-front-dev
    build:
      context: ./approt-doc-front
      dockerfile: dev.Dockerfile
    volumes:
      - ./approt-doc-front:/usr/src/app
    ports:
      - 3000:3000

  server:
    container_name: approt-doc-back-dev
    build:
      context: ./approt-doc-back
      dockerfile: dev.Dockerfile
    volumes:
      - ./approt-doc-back:/usr/src/app
    environment: 
      - PORT=3001
      - MONGODB_URI=mongodb+srv://containersUser:ML9HqqkEIfhll6QZ@datacluster.3bdzc.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

  nginx:
    container_name: reverse-proxy
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app